language: SQL
dist: trusty
sudo: true

matrix:
  include:
    - name: sql
      env: TEST="sql"

    - name: extension
      env: TEST="extension"

    - name: pgxn
      env: TEST="pgxn"

    - name: extension-nobackup
      env: TEST=extension NO_BACKUP=1

    - name: pgxn-nobackup
      env: TEST=pgxn NO_BACKUP=1

  allow_failures:
    - name: extension
    - name: pgxn

services:
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

before_install:
    - psql -c 'create database pgmemento_testdb;' -U postgres
    - psql --version

script:
    - if [[ $TEST == "sql" ]] ; then psql -U postgres -d pgmemento_testdb -a -f TEST.sql ; fi
    - if [[ $TEST == "extension" ]] ; then ./extension/tests/run.sh $NO_BACKUP ; fi
    - if [[ $TEST == "pgxn" ]] ; then ./extension/pgxn/tests/run.sh $NO_BACKUP ; fi
