language: SQL
dist: trusty
sudo: true

services:
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

before_install:
    - psql -c 'create database pgmemento_testdb;' -U postgres
    - psql --version

script:
    - psql -U postgres -d pgmemento_testdb -a -f TEST.sql
    - ./extension/tests/run.sh
