language: SQL
dist: trusty
sudo: true

addons:
  postgresql: "9.5"

before_script:
    - psql -c 'create database pgmemento_testdb;' -U postgres
    - psql --version

script:
    - psql -U postgres -d pgmemento_testdb -a -f TEST.sql
