language: SQL
dist: trusty
sudo: true

matrix:
  include:
    - name: sql
      env: TEST=sql

    - name: extension
      env: TEST=extension PG=95

    - name: pgxn
      env: TEST=pgxn PG=95

    - name: extension-9.5
      env: TEST=extension PG=95 NO_BACKUP=1

    - name: extension-9.6
      env: TEST=extension PG=96 NO_BACKUP=1

    - name: extension-10
      env: TEST=extension PG=10 NO_BACKUP=1

    - name: extension-11
      env: TEST=extension PG=11 NO_BACKUP=1

    - name: pgxn-9.5
      env: TEST=pgxn PG=95 NO_BACKUP=1

    - name: pgxn-9.6
      env: TEST=pgxn PG=96 NO_BACKUP=1

    - name: pgxn-10
      env: TEST=pgxn PG=10 NO_BACKUP=1

    - name: pgxn-11
      env: TEST=pgxn PG=11 NO_BACKUP=1

  allow_failures:
    - name: extension
    - name: pgxn

services:
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

before_install:
    - psql -c 'create database pgmemento_testdb;' -U postgres
    - psql --version

script:
    - if [[ $TEST == "sql" ]] ; then psql -U postgres -d pgmemento_testdb -a -f TEST.sql ; fi
    - if [[ $TEST == "extension" ]] ; then ./extension/tests/run.sh $PG $NO_BACKUP ; fi
    - if [[ $TEST == "pgxn" ]] ; then ./extension/pgxn/tests/run.sh $PG $NO_BACKUP ; fi
