name: pgmemento-tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ext: [extension, pgxn]
        pg: [9.6, 10, 11, 12, 13]
    services:
      postgres:
        image: postgis/postgis:${{ matrix.pg }}-3.1
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          TEST: ${{ matrix.ext }}
          PG: ${{ matrix.pg }}
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: create new empty database
        run: psql -c 'create database pgmemento_testdb;' -U postgres
      - name: Run pgMemento tests
        run: |
          if [[ $TEST == "extension" ]] ; then ./extension/tests/run.sh $PG ; fi
          if [[ $TEST == "pgxn" ]] ; then ./extension/pgxn/tests/run.sh $PG ; fi
